"""Product recommendations section — auto-generated by Shopify."""
from ...core.section import Section, SectionPreset, SectionRegistry
from ...core.setting import (
    Text, Select, SelectOption, Checkbox, Number, Range, Header,
)


class ProductRecommendationsSection(Section):
    type = "product-recommendations"
    name = "Product recommendations"
    tag = "section"
    class_name = "product-recommendations"
    limit = 1
    available_on = ["product"]

    settings = [
        Header("Content"),
        Text("heading", label="Heading", default="You may also like"),
        Header("Layout"),
        Range("products_per_row", label="Products per row",
              min=2, max=6, step=1, default=4, unit="products"),
        Range("products_to_show", label="Max products to show",
              min=2, max=12, step=1, default=4, unit="products"),
        Select("image_ratio", label="Image aspect ratio",
               options=[
                   SelectOption("adapt", "Adapt to image"),
                   SelectOption("square", "Square (1:1)"),
                   SelectOption("portrait", "Portrait (4:5)"),
                   SelectOption("landscape", "Landscape (3:2)"),
               ],
               default="adapt"),
        Header("Product card"),
        Checkbox("show_vendor", label="Show vendor", default=False),
        Checkbox("show_price", label="Show price", default=True),
        Checkbox("show_quick_add", label="Show quick add button", default=False),
    ]

    presets = [
        SectionPreset(name="Product recommendations", settings={
            "heading": "You may also like",
            "products_per_row": 4,
            "products_to_show": 4,
            "image_ratio": "adapt",
            "show_price": True,
        }),
    ]

    template = """
<section
  class="product-recommendations"
  {{ section.shopify_attributes }}
  data-product-recommendations
>
  <div class="page-width">
    {%- if section.settings.heading -%}
      <h2 class="product-recommendations__heading">{{ section.settings.heading }}</h2>
    {%- endif -%}

    <div
      class="product-recommendations__grid"
      data-columns="{{ section.settings.products_per_row }}"
      data-limit="{{ section.settings.products_to_show }}"
    >
      {%- for i in (1..section.settings.products_to_show) -%}
        <div class="product-recommendations__placeholder">
          <div class="c-card__media"></div>
        </div>
      {%- endfor -%}
    </div>
  </div>
</section>
    """

    styles = """
.product-recommendations {
  padding: 3rem 0;
  border-top: 1px solid var(--color-border, #eee);
}

.product-recommendations__heading {
  font-family: var(--font-heading-family);
  font-size: clamp(1.5rem, 3vw, 2rem);
  font-weight: 600;
  margin: 0 0 2rem;
  text-align: center;
}

.product-recommendations__grid {
  display: grid;
  gap: var(--grid-gap, 1.5rem);
  grid-template-columns: repeat(2, 1fr);
}

.product-recommendations__grid[data-columns="3"] { grid-template-columns: repeat(3, 1fr); }
.product-recommendations__grid[data-columns="4"] { grid-template-columns: repeat(4, 1fr); }

.product-recommendations__placeholder .c-card__media {
  aspect-ratio: 4/5;
  background: var(--color-surface, #f5f5f5);
  border-radius: var(--radius-md, 8px);
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

@media (max-width: 767px) {
  .product-recommendations__grid,
  .product-recommendations__grid[data-columns="3"],
  .product-recommendations__grid[data-columns="4"] {
    grid-template-columns: repeat(2, 1fr);
  }
}

@media (prefers-reduced-motion: reduce) {
  .product-recommendations__placeholder .c-card__media { animation: none; }
}
    """


SectionRegistry.register(ProductRecommendationsSection)
